// micro-app-react/src/App.jsx
import React, { useState, useEffect } from 'react';
import { Menu } from "antd";
import Home from './pages/home';
import List from './pages/list';
import Status from './pages/status';
import { BrowserRouter as Router, Route, Switch, Link } from "react-router-dom";

const menus = [
  {
    key: "react",
    route: "/react",
    title: "主页"
  },
  {
    key: "react-list",
    route: "/react/list",
    title: "列表页"
  },
  {
    key: "react-status",
    route: "/react/status",
    title: "状态页"
  },
  {
    key: "vue",
    route: "/vue",
    title: "Vue 子应用"
  }
]

const App = () => {
  const [refresh, setRefresh] = useState(0);
  const [selectedKeys, setSelectKeys] = useState(['react']);
  useEffect(() => {
    const { pathname } = window.location;
    const menu = menus.find(item => item.route === pathname);
    setSelectKeys(() => ([menu ? menu.key : 'react']));
  }, [refresh]);

  return (
    <Router>
      <section>
        <Menu
          onClick={() => setRefresh(refresh => ++refresh)}
          selectedKeys={selectedKeys}
          mode="horizontal">
          {
            menus.map(item => (
              <Menu.Item key={item.key}>
                <Link to={item.route}>{item.title}</Link>
              </Menu.Item>
            ))
          }
        </Menu>
        <Switch>
          <Route exact path='/' component={Home} />
          <Route exact path='/react' component={Home} />
          <Route path='/react/list' component={List} />
          <Route path='/react/status' component={Status} />
        </Switch>
      </section>
    </Router>
  )
}

export default App;

// micro-app-vue/src/App.vue
<template>
  <div id="app">
     <a-menu :selectedKeys="[currentRoute]" mode="horizontal" theme="dark">
      <a-menu-item 
        v-for="(item) in menus" 
        :key="item.key"
        >
        <router-link :to="item.route">{{item.title}}</router-link>
      </a-menu-item>
     </a-menu>
    <router-view :key="(new Date()).getTime()" />
  </div>
</template>

<script>
export default {
  name: 'App',

  data() {
    return {
      menus: [
        {
          key: "vue",
          route: "/vue",
          title: "主页"
        },
        {
          key: "vue-list",
          route: "/vue/list",
          title: "列表页"
        },
        {
          key: "vue-status",
          route: "/vue/status",
          title: "状态页"
        },
        {
          key: "react",
          route: "/react",
          title: "React 子应用"
        }
      ]
    }
  },

  created(){
    window.test = true;
  },
  
  computed: {
    currentRoute() {
      const menu = this.menus.find(item => item.route === this.$route.path)
      return menu ? menu.key : "vue";
    }
  },
}
</script>

<style>
</style>
