// micro-app-react/src/App.jsx
import React, { useState, useEffect } from 'react';
import { Menu } from "antd";
import Home from './pages/home';
import List from './pages/list';
import Status from './pages/status';
import { BrowserRouter as Router, Route, Switch, Link } from "react-router-dom";

const menus = [
  {
    key: "react",
    route: "/react",
    title: "主页"
  },
  {
    key: "react-list",
    route: "/react/list",
    title: "列表页"
  },
  {
    key: "react-status",
    route: "/react/status",
    title: "状态页"
  },
  {
    key: "vue",
    route: "/vue",
    title: "Vue 子应用"
  }
]

const App = () => {
  const [refresh, setRefresh] = useState(0);
  const [selectedKeys, setSelectKeys] = useState(['react']);
  useEffect(() => {
    const { pathname } = window.location;
    const menu = menus.find(item => item.route === pathname);
    setSelectKeys(() => ([menu ? menu.key : 'react']));
  }, [refresh]);

  return (
    <Router>
      <section>
        <Menu
          onClick={() => setRefresh(refresh => ++refresh)}
          selectedKeys={selectedKeys}
          mode="horizontal">
          {
            menus.map(item => (
              <Menu.Item key={item.key}>
                <Link to={item.route}>{item.title}</Link>
              </Menu.Item>
            ))
          }
        </Menu>
        <Switch>
          <Route exact path='/' component={Home} />
          <Route exact path='/react' component={Home} />
          <Route path='/react/list' component={List} />
          <Route path='/react/status' component={Status} />
        </Switch>
      </section>
    </Router>
  )
}

export default App;

// micro-app-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
  title = 'micro-app-angular';

  menus = [
    {
      key: "angular",
      route: "/",
      title: "主页"
    },
    {
      key: "angular-list",
      route: "/list",
      title: "列表页"
    }
  ]

  get currentRoute() {
    const menu = this.menus.find(item => item.route === window.location.pathname)
    return menu ? menu.key : "angular";
  }
}

<section>
  <ul nz-menu nzMode="horizontal" nzTheme="dark">
    <li *ngFor="let item of menus" nz-menu-item [nzSelected]="currentRoute === item.key">
      <a [routerLink]="item.route">{{item.title}}</a>
    </li>
  </ul>
  
  <section style="padding: 20px;">
    <router-outlet></router-outlet>
  </section>
</section>
