// micro-app-vue/src/pages/status/index.vue
<template>
  <a-card title="Vue 公共状态页">
    <a-button type="primary" @click="dec"> - </a-button>
    <span style="margin: 20px;font-size: 24px; color: red;">count: {{count}}</span>
    <a-button type="primary" @click="add"> + </a-button>
  </a-card>
</template>
<script>

import { dispatch, subscribe, getState } from '../../../../store/plugin';

export default {
  name: "Status",

  data() {
    return {
      count: getState().count,
      unSubscribe: null
    }
  },

  methods: {
    add() {
      dispatch({ type: "INCREMENT" });
    },

    dec() {
      dispatch({ type: "DECREMENT" });
    }
  },

  created() {
    this.unSubscribe = subscribe(() => {
      this.count = getState().count;
    });
  },

  destroyed() {
    this.unSubscribe && this.unSubscribe();
  }
}
</script>

// micro-app-react/src/pages/status/index.jsx
import React, { useState, useEffect } from "react";
import { Card, Button } from "antd";
import { dispatch, subscribe, getState } from '../../utils/plugin';

const Status = () => {
  const [count, setCount] = useState(getState().count);
  useEffect(() => {
    const unSubscribe = subscribe(() => setCount(getState().count));
    return unSubscribe;
  }, []);
  
  return (
    <Card title="React 子应用公共状态页">
      <Button type="primary" onClick={() => dispatch({ type: "DECREMENT" })}> - </Button>
      <span style={{ margin: 20, color: "blue", fontSize: 24 }}>count: {count}</span>
      <Button type="primary" onClick={() => dispatch({ type: "INCREMENT" })}> + </Button>
    </Card>
  )
}

export default Status;
